# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
- task: PackerBuild@1
  inputs:
    templateType: 'builtin'
    ConnectedServiceName: 'Mohan-Pay-As-You-Go(1)(fe7e7d3e-7676-4748-a967-348a8ca48209)'
    isManagedImage: true
    location: 'westus2'
    storageAccountName: 'saimageautomation'
    azureResourceGroup: 'image-automation'
    baseImageSource: 'default'
    baseImage: 'Canonical:UbuntuServer:18.04-LTS:linux'
    packagePath: '$(System.DefaultWorkingDirectory)'
    deployScriptPath: 'script.sh'
    imageUri: 'ubuntu-azure-devops-test'
  displayName: 'Run a multi-line script'
