trigger:
  branches:
    include:
    - master

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

steps:
- task: riezebosch.Packer.PackerTool.PackerTool@0
  displayName: 'Use Packer 1.4.4'
  inputs:
    version: 1.4.4

- task: Bash@3
  displayName: 'Packer environment Validation'
  inputs:
    targetType: filePath
    filePath: ./pipelines/validation.sh

- bash: |
   ls -al
   packer version
   packer build ubuntu-hardening.json
   packer build windows.json
  displayName: 'Build Linux Image'
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    TENANT_ID: $(TENANT_ID)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
